eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/ #this ia used without docker 
      # defaultZone: http://discovery-service:8090/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

# spring:
#   cloud:
#     compatibility-verifier:
#       enabled: false


# management:
#   info:
#     git:
#       mode: full                  # Git info for actuator / info endpoint
#   endpoints:
#     web:
#       exposure:
#         include: "*"              # expose all actuator endpoints
#   metrics:
#     tags:
#       application: ${spring.application.name}   # dynamic application name from env
#   tracing:
#     enabled: ${MANAGEMENT_TRACING_ENABLED:true}   # enable tracing via env variable
#     sampling:
#       probability: 1.0           # tracing sampling probability
#   zipkin:
#     tracing:
#       endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://tempo:9411/api/v2/spans}  # Zipkin/Tempo endpoint from env
